### ISSUE TITLE
NameError in Oils#show

### ISSUE THREAD

**Issue by hh747hh** [ga-wdi-exercises/project2#515] opened 2016-03-23 15:55 UTC
![screen shot 2016-03-23 at 11 51 45 am](https://cloud.githubusercontent.com/assets/16959988/13991228/b4e067d8-f0ed-11e5-998c-872da896a09e.png)

I am trying to add delete function to comment but it can't read comment...

**Comment by hh747hh** [comment] 2016-03-23 15:55
``` rb
class CommentsController < ApplicationController
  def create
    @oil = Oil.find(params[:oil_id])
    @comment = @oil.comments.create(comment_params)
    redirect_to oil_path(@oil)
  end

  def new
    @oil = Oil.find(params[:oil_id])
    @comment = Comment.new
  end

  def create
    @oil = Oil.find(params[:oil_id])
    @comment = @oil.comments.create(comment_params)
    redirect_to oil_path(@oil)
  end

  def edit
    @oil = Oil.find(params[:oil_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @oil = Oil.find(params[:oil_id])
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to oil_path(@oil)
  end

  def destroy
    @oil = Oil.find(params[:oil_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to oil_path(@oil)
  end
```

**Comment by hh747hh** [comment] 2016-03-23 15:56
Oops I thought I put ```

**Comment by RobertAKARobin** [comment] 2016-03-23 15:57
Have you defined a variable called `comment` anywhere?

Remember `wombat` and `@wombat` are completely different.

**Comment by hh747hh** [comment] 2016-03-23 16:00
you mean in controller? 

``` rb
def destroy
    @oil = Oil.find(params[:oil_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to oil_path(@oil)
  end
```

**Comment by RobertAKARobin** [comment] 2016-03-23 16:02
That defines `@comment`, but the issue is you're trying to use `comment`. `@comment` and `comment` are completely different.

Just because you defined `@comment` doesn't mean you also have a variable called `comment`. In the same way, just because you defined `zwombat` doesn't mean you also have a variable called `wombat`. If you want `zwombat` and `wombat`, you have to have both `zwombat = something` and `wombat = something_else`.

**Comment by hh747hh** [comment] 2016-03-23 16:02
```
<%= link_to "Edit", edit_oil_comment_path(@oil, @comment) %>
<%= link_to "Delete", oil_comment_path(@oil, @comment), method: :delete %>
```

this didn't work

**Comment by RobertAKARobin** [comment] 2016-03-23 16:02
Can you be more specific? "Didn't work" doesn't tell us much. Are you getting a different error?

**Comment by hh747hh** [comment] 2016-03-23 16:04
![screen shot 2016-03-23 at 12 03 47 pm](https://cloud.githubusercontent.com/assets/16959988/13991645/6439fca2-f0ef-11e5-97ad-08f39e8c98f1.png)

**Comment by hh747hh** [comment] 2016-03-23 16:05
![screen shot 2016-03-23 at 12 05 25 pm](https://cloud.githubusercontent.com/assets/16959988/13991726/96a63b60-f0ef-11e5-8011-6215d19e9963.png)

**Comment by hh747hh** [comment] 2016-03-23 16:06
I see edit route is edit_oil_comment

so I input edit_oil_comment_path

**Comment by RobertAKARobin** [comment] 2016-03-23 16:13
Can you show me your `show` controller action?

**Comment by hh747hh** [comment] 2016-03-23 16:16
``` rb
def show
    @oil =Oil.find(params[:id])
    @comment = Comment.find(params[:id])
  end
```

**Comment by hh747hh** [comment] 2016-03-23 16:19
```
class CommentsController < ApplicationController
  def create
    @oil = Oil.find(params[:oil_id])
    @comment = @oil.comments.create(comment_params)
    redirect_to oil_path(@oil)
  end

  def new
    @oil = Oil.find(params[:oil_id])
    @comment = Comment.new
  end

  def create
    @oil = Oil.find(params[:oil_id])
    @comment = @oil.comments.create(comment_params)
    redirect_to oil_path(@oil)
  end

  def edit
    @oil = Oil.find(params[:oil_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @oil = Oil.find(params[:oil_id])
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to oil_path(@oil)
  end


  def show
    @oil =Oil.find(params[:id])
    @comment = Comment.find(params[:id])
  end



  def destroy
    @oil = Oil.find(params[:oil_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to oil_path(@oil)

  end


  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end

end
```

**Comment by hh747hh** [comment] 2016-03-23 16:20
Sorry I thought I put 

```
```

**Comment by RobertAKARobin** [comment] 2016-03-23 16:26
Notice that the `edit_oil_comment_path` URL looks like this:

```
/oils/:oil_id/comments/:id/edit
```

| If you go to localhost:1234/... | it matches this route | and `params[:id]` equals | `params[:tag_id]` |
| :-- | :-- | :-- | :-- |
| `/tags/32` | `/tags/:id` | 32 | nil |
| `/tags/32/items` | `/tags/:tag_id/items` | nil | 32 |
| `/tags/32/items/19` | `/tags/:tag_id/items/:id` | 19 | 32 |

In your controller, you have:

``` rb
@oil =Oil.find(params[:id])
@comment = Comment.find(params[:id])
```

Both are using `params[:id]`. If your URL is `/oils/32/comments/19/edit`, that's as if you were writing:

```
@oil = Oil.find(19)
@comment = Comment.find(19)
```

Odds are, the oil and the comment don't have the same ID! You probably want:

```
@oil = Oil.find(params[:oil_id])
@comment = Comment.find(params[:id])
```

**Comment by RobertAKARobin** [comment] 2016-03-23 17:09
Been a while so I'm going to close this. Feel free to re-open or create a new issue!

**Closed as completed by RobertAKARobin** 2016-03-23 17:09 UTC
