### ISSUE TITLE
Create method in controller. 

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#631] opened 2016-08-08 16:33 UTC
I'm having an issue using the button_to helper - 

`<%=button_to 'New', {:controller => "emojitweets", :action => "create", :tweet_id => tweet.id, :emoji_id=>emoji.id, :user_id => current_user}%>`

This will render in the view, but when I click the generated button I get this error
"param is missing or the value is empty"

Parameters:

{"authenticity_token"=>"Tzcb1YHkMZR8g3sTOlDbsWKbsyama0QbRyaBr4Fjve4yG46J058yeW/MM42Asthdz5iuj9qNzfbLHK/mf5/GpQ==", "emoji_id"=>"1", "user_id"=>"1", "tweet_id"=>"3"}

All my parameters exists, but obviously something is getting hung up. 

I've verified that my POST method works, but only by navigating to a separate (/new) page and using a form. 

I'm wondering if I can generate a POST request from the index view using a format like I have above.

**Comment by andrewsunglaekim** [comment] 2016-08-08 16:36
can you post your create action thats handling that request

**Comment by ghost** [comment] 2016-08-08 16:38
'@emojitweet = Emojitweet.new(emojitweet_params)
@emojitweet.save
binding.pry
redirect_to root_path`

The error is being caught when it tries to call the params method

**Comment by ghost** [comment] 2016-08-08 16:43
I think I know what the issue is, but not how to fix it.
In:
'    def emojitweet_params
        params.require(:emojitweet).permit!
    end'

:emojitweet is just not being recognized when I try and do a post this way

**Comment by andrewsunglaekim** [comment] 2016-08-08 17:13
yeah, because it's just key value pairs and not a nested name attribute in a form.

**Comment by andrewsunglaekim** [comment] 2016-08-08 17:14
i'm going to close this for now since you said you figured it out in passing, reopen if its still causing issues. Incidentally that is what the issue is . 😄

**Closed as completed** 2016-08-08 17:14 UTC
