### ISSUE TITLE
Images not sizing properly with CSS

### ISSUE THREAD

**Issue by merubin** [ga-wdi-exercises/project2#735] opened 2016-10-19 14:33 UTC
My pictures for Twitter etc are not sizing based on my css social tag.

<img width="465" alt="screen shot 2016-10-19 at 10 28 27 am" src="https://cloud.githubusercontent.com/assets/19254862/19523011/32dcdc4a-95e7-11e6-90ca-6ab411b9e93c.png">

```
#social img{
    width: 25px;
    margin: 0 5px;
    -webkit-transition: -webkit-transform .08s ease-in-out;
    transition: transform .08s ease-in-out;
}

#social img:hover{
    -webkit-transform: rotate(9deg);
    transform: rotate(9deg);
}

#footer p{
    color: #5b6164;
    opacity: 0.3;
    font-size: 0.7em;
}

```

![image](https://cloud.githubusercontent.com/assets/19254862/19523040/4c0fd0c8-95e7-11e6-963a-46d24d720370.png)

As you can see the icons are BIG

Here is the .erb

```
    <div id="footer">
      <div id="social">
        <%= image_tag "nav/social/twitter.png" %>
        <%= image_tag "nav/social/email.png" %>
        <%= image_tag "nav/social/instagram.png" %>
      </div>
      <div>
        <p>Copyright &copy; 2016 Rubin IT Solutions</p>


```

Any hints?  for sizing bitmaps here correctly?

**Comment by jshawl** [comment] 2016-10-19 14:54
try adding `display:inline-block` to your css for images

**Comment by merubin** [comment] 2016-10-19 15:12
That did not work.  I seem to be able to change the height but not the width?  I'm not sure why. Also the images are not floating up besides each other.

**Comment by amaseda** [comment] 2016-10-19 15:26
When inspecting the element, what does it say its width is / where is it inheriting that width from?

Also can you push up your most recent code and link to your repo? Can take a closer look.

**Comment by merubin** [comment] 2016-10-19 15:33
![image](https://cloud.githubusercontent.com/assets/19254862/19525613/8c38ef92-95ef-11e6-9ac8-cf191b12301d.png)

Inheriting from body.  Says size is 160x160 
Just committed and pushed upt

**Comment by amaseda** [comment] 2016-10-19 16:23
From what I can see in dev tools, the width is being overwritten by this selector `#show-portfolio-wrapper nav img`. When I unselect that in dev tools, it then switches to the intended 25px width.

**Comment by amaseda** [comment] 2016-10-19 17:00
Closing since you confirmed it was fixed IRL!

**Closed as completed by amaseda** 2016-10-19 17:00 UTC
