### ISSUE TITLE
action controller url generation error 

### ISSUE THREAD

**Issue by adrianshep** [ga-wdi-exercises/project2#88] opened 2015-08-04 17:41 UTC
On my index page, I have a show link next to my store name. When I comment it out, the index page loads. When I uncomment it, I get the below error messages. I've been trying to figure out how to pass in "store" 's id.

```
ActionController::UrlGenerationError in Stores#index
No route matches {:action=>"show", :controller=>"stores", :id=>nil, :user_id=>"1"} missing required keys: [:id]
```

```
<% @stores.each do |store| %>
  <li><%= store.name %></li>
<%= link_to("Show", user_store_path(current_user, store)) %>
```

```
class StoresController < ApplicationController
  # before any post action happens, it will authenticate the user
    before_action :authenticate_user!

    # another devise helper method that retrieves the user object that has been authenticated
    def index
      @stores = current_user.stores
    end

    def show
      @store = Store.find(params[:id])
    end
```

**Comment by RobertAKARobin** [comment] 2015-08-04 17:44
Can you push your code to Github and link to your repository?

**Comment by adrianshep** [comment] 2015-08-04 17:48
https://github.com/adrianshep/price-parser.git
and select "working_branch"

**Comment by RobertAKARobin** [comment] 2015-08-04 17:56
Thanks! The problem is `@stores = current_user.stores`. The current user doesn't have any stores, so when the `link_to` helper tries to get the store ID, which doesn't exist, it yells at you.

You might try something like this:

``` erb
  <% if @stores.count > 0 %>
    <% @stores.each do |store| %>
    <li><%= store.name %></li>
    <%= link_to("Show", user_store_path(current_user, store)) %>
    <%#= link_to("Edit", '#', :class => 'action edit') %>
    <%#= link_to("Delete", store_path(store), :class => 'action delete') %>
    <% end %>
  <% end %>
```

**Comment by jshawl** [comment] 2015-08-04 17:58
Depending on the url, some will have a user id and some will not. Closing for now but please reopen if you have issues!

Check if the user id is present:

```
class StoresController
    def index
      if params[:user_id]
        @stores = Store.where(user_id: params[:user_id])
    else
        @stores = Store.all
    end
end
```

**Closed as completed by jshawl** 2015-08-04 17:58 UTC

**Comment by adrianshep** [comment] 2015-08-04 18:07
I tried out Jese's solution and it's working, thank you!
