### ISSUE TITLE
Error seeding data base

### ISSUE THREAD

**Issue by jeffreyeaton76** [ga-wdi-exercises/project2#503] opened 2016-03-22 21:07 UTC
I’m trying to associate comments with users in my seed data and got the following error:

```
ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  update or delete on table "users" violates foreign key constraint "fk_rails_5b5ddfd518" on table "posts"
DETAIL:  Key (id)=(1) is still referenced from table "posts".
: DELETE FROM "users" WHERE "users"."id" = $1
```

a sample of my seed data looks like this:

```
jeff = User.create(username:'jeff', password:'jeff', first_name: "Jeffrey", last_name: "Eaton", city: "Washington", state: "DC")

a = jeff.posts.create(bird: "eagle", img_url: "http://www.birds-of-north-america.net/images/northern-cardinal-12.jpg", date_seen: "01/17/2015", city: "Washington", state: "DC", field_notes: "Blah Blah blah.")

a.comments.create(body:"Nice eagle you've got there.", user: dan)
```

and the Posts migration looks like this:

```
class CreatePosts < ActiveRecord::Migration
  def change
    create_table :posts do |t|
      t.string :bird
      t.string :img_url
      t.string :date_seen
      t.string :city
      t.string :state
      t.text :field_notes
      t.references :user, index: true, foreign_key: true
      t.timestamps null: false
    end
  end
end
```

**Comment by RobertAKARobin** [comment] 2016-03-22 21:14
Do you have something that deletes the User table?

**Comment by RobertAKARobin** [comment] 2016-03-22 21:15
If you're not sure, go back and check all your migrations!

**Comment by jeffreyeaton76** [comment] 2016-03-22 21:16
You mean at the top of the seed file? I do have this . . .

```
User.destroy_all
Post.destroy_all
Comment.destroy_all
```

**Comment by jeffreyeaton76** [comment] 2016-03-22 21:19
I only have three migration files and they look like this, which I think is ok? 

```
class CreateUsers < ActiveRecord::Migration
  def change
    create_table :users do |t|
      t.string :username
      t.string :password
      t.string :first_name
      t.string :last_name
      t.string :city
      t.string :state
    end
  end
end


class CreatePosts < ActiveRecord::Migration
  def change
    create_table :posts do |t|
      t.string :bird
      t.string :img_url
      t.string :date_seen
      t.string :city
      t.string :state
      t.text :field_notes
      t.references :user, index: true, foreign_key: true
      t.timestamps null: false
    end
  end
end

class CreateComments < ActiveRecord::Migration
  def change
    create_table :comments do |t|
      t.text :body
      t.references :post, index: true, foreign_key: true
      t.references :user, index: true, foreign_key: true
      t.timestamps null: false
    end
  end
end
```

**Comment by RobertAKARobin** [comment] 2016-03-22 21:20
Did you DCMS?

**Comment by jeffreyeaton76** [comment] 2016-03-22 21:21
Indeed. That's where the error is coming from. At the rake db:seed stage. I did an extra DCM to be sure.

**Comment by RobertAKARobin** [comment] 2016-03-22 21:22
Can you push your code to Github so we can look?

**Comment by jeffreyeaton76** [comment] 2016-03-22 21:26
Ok, I have advanced one step. I did another DCMS and seeding worked. BUT the whole point of rearranging the models with foreign keys was to solve the `undefined method`first_name' for nil:NilClass` error when it tries to render the author of a comment. 

The troublesome bit of code for that is:

```
  <% @comment.reverse.each do |comment| %>
  <div class="comments"><p><i><%= comment.body %></i></p>
  <p><i>-- <%= comment.user.first_name %> <%= comment.user.last_name %></i></div>
  <% end %>
```

and the variables are sourced at 

```
def show
    @post = Post.find(params[:id])
    @comment = @post.comments
  end
```

**Comment by RobertAKARobin** [comment] 2016-03-22 21:48
Check again to make sure each comment has a user, or put in a conditional so that it doesn't try to get the first name of the user of the user doesn't exist.

**Comment by RobertAKARobin** [comment] 2016-03-22 21:50
You might try this in your Rails console to count how many user-less comments there are.

```
Comment.where(user: nil).count
```

**Comment by jeffreyeaton76** [comment] 2016-03-22 21:51
It's zero.

**Comment by jeffreyeaton76** [comment] 2016-03-22 21:53
Do I need a line like the last one (it's wrong but do I need to connect the users and comments better)?

```
  def show
    @post = Post.find(params[:id])
    @comment = @post.comments
    @comment.user = User.find(params[@comment.user_id])
  end
```

**Comment by RobertAKARobin** [comment] 2016-03-22 21:53
Can you show me the controller for this view?

**Comment by jeffreyeaton76** [comment] 2016-03-22 21:54
```
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comment = @post.comments
    @comment.user = User.find(params[@comment.user_id])
  end

  def new
    redirect_to root_path unless @current_user
    @post = Post.new
  end

  def create
    redirect_to root_path unless @current_user
    @post = Post.new(post_params)
    @post.user = @current_user
    if @post.save
      redirect_to @post
    end
  end

  def edit
    redirect_to root_path unless @current_user
    @post = Post.find(params[:id])
  end

  def update
    redirect_to root_path unless @current_user
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    redirect_to root_path unless @current_user
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to :action => :index
  end

  private

  def post_params
    params.require(:post).permit(:bird, :img_url, :date_seen, :city, :state, :field_notes)
  end

end
```

**Comment by RobertAKARobin** [comment] 2016-03-22 21:54
You can't do `@comment.user` if `@comment` is actually _several_ comments. Your variable isn't named properly.

**Comment by jeffreyeaton76** [comment] 2016-03-22 21:54
It's currently one per post, though it will be more eventually.

**Comment by RobertAKARobin** [comment] 2016-03-22 21:55
It doesn't matter. `@post.comments` will always return an array, even if it's an array with 1 or 0 things in it.

**Comment by jeffreyeaton76** [comment] 2016-03-22 21:58
Back to original `nil` error. Did I rename the wrong variable? I also took out that crazy line `@comment.user = User.find(params[@comment.user_id])` because I was just making things up and assume it couldn't be right.

``` rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def new
    redirect_to root_path unless @current_user
    @post = Post.new
  end

  def create
    redirect_to root_path unless @current_user
    @post = Post.new(post_params)
    @post.user = @current_user
    if @post.save
      redirect_to @post
    end
  end

  def edit
    redirect_to root_path unless @current_user
    @post = Post.find(params[:id])
  end

  def update
    redirect_to root_path unless @current_user
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    redirect_to root_path unless @current_user
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to :action => :index
  end

  private

  def post_params
    params.require(:post).permit(:bird, :img_url, :date_seen, :city, :state, :field_notes)
  end

end
```

**Comment by jeffreyeaton76** [comment] 2016-03-22 22:01
If you need it: https://github.com/jeffreyeaton76/lifelist

**Comment by RobertAKARobin** [comment] 2016-03-22 22:01
Well, that looks correct to me. So how about this:

``` erb
  <% @comment.reverse.each do |comment| %>
  <div class="comments"><p><i><%= comment.body %></i></p>
  <p><i>-- <%= comment.user %></i></div>
  <% end %>
```

This won't fix the problem, but it'll make it obvious which particular comment is being problematic. Just look for the one that doesn't have anything after the comment's body.

**Comment by jeffreyeaton76** [comment] 2016-03-22 22:03
It's all of them! But in the console they're totally there.

**Comment by jeffreyeaton76** [comment] 2016-03-22 22:07
```
p = Post.find(1) 
p.comments.find(1).user.first_name
```

this, in the console, returns the desired value.

**Comment by RobertAKARobin** [comment] 2016-03-22 22:15
I'm running this on my computer. This is bizarre.

**Comment by jeffreyeaton76** [comment] 2016-03-22 22:16
Thank goodness. I feel much better even if it turns out to be a single character error in the end. The version I pushed still has that crazy line in the posts#show.

**Comment by RobertAKARobin** [comment] 2016-03-22 22:18
The issue is this line:

``` erb
<%= form_for ([@post, @post.comments.build]) do |f| %>
```

The `.build` creates a "dummy" comment, but it's still included in `@post.comments`.

Try this instead:

``` erb
<%= form_for new_post_comment_path(@post) do |f| %>
```

I **hate** this error. I've gotten it so many times and it stumps me each time.

**Comment by jeffreyeaton76** [comment] 2016-03-22 22:21
Dear lord in heaven, it works. Extraordinary effort on your part. Many thanks

**Closed as completed** 2016-03-22 22:21 UTC
