### ISSUE TITLE
Duplicate column and index

### ISSUE THREAD

**Issue by merubin** [ga-wdi-exercises/project2#696] opened 2016-10-15 17:09 UTC
I've created my users table and need to add devise to put in user and password functionality.
my original data model had a email column but devise also adds an email column.
I successfully removed the email from my database with 
`rails generate migration remove_email_from_users email:string`

The thing I cannot back out is the index.  I am getting the following error:

```
PG::UniqueViolation: ERROR:  could not create unique index "index_users_on_email"
DETAIL:  Key (email)=() is duplicated.
: CREATE UNIQUE INDEX  "index_users_on_email" ON "users"  ("email")
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `async_exec'
```

Following this link from google [http://stackoverflow.com/questions/9028387/whats-the-correct-syntax-for-remove-index-in-a-rails-3-1-0-migration](url)
I've tried adding the following to the 20161015162837_add_devise_to_users.rb file. before the creation of the index which is failing:
`remove_index(:users, :name => 'index_users_on_email')`
That gives the following error:
![image](https://cloud.githubusercontent.com/assets/19254862/19411897/0fd53448-92d8-11e6-99c5-f3f5ccf62a8a.png)

So it is not there when I want to delete it and it is there when I want to add it.  Please Help!
I'm working on a branch so I can easily back out. but I would like to get the current user put into the model so I can continue work on my app.  I have User CRUD already working now and before I move to CRUD on others I wanted to get this working today.

Thanks.

**Comment by jshawl** [comment] 2016-10-15 17:42
What does your migration file look like? Are there two migrations for users, both with an email column

**Comment by merubin** [comment] 2016-10-15 17:55
My first (initial)  migration file  created the users table:

```
class CreateUsers < ActiveRecord::Migration[5.0]
  def change
    create_table :users do |t|
      t.string :name
      t.string :userid
      t.string :password
      t.string :email
      t.string :avatar_url

      t.timestamps
    end
  end
end

```

Then there is the remove migration file

```
class RemoveEmailFromUsers < ActiveRecord::Migration[5.0]
  def change
    remove_column :users, :email, :string
  end
end
```

Finally the Devises migration file 

```
class AddDeviseToUsers < ActiveRecord::Migration[5.0]
  def self.up
    change_table :users do |t|
      ## Database authenticatable
      t.string :email,              null: false, default: ""
      t.string :encrypted_password, null: false, default: ""

      ## Recoverable
      t.string   :reset_password_token
      t.datetime :reset_password_sent_at

      ## Rememberable
      t.datetime :remember_created_at

      ## Trackable
      t.integer  :sign_in_count, default: 0, null: false
      t.datetime :current_sign_in_at
      t.datetime :last_sign_in_at
      t.inet     :current_sign_in_ip
      t.inet     :last_sign_in_ip

      ## Confirmable
      # t.string   :confirmation_token
      # t.datetime :confirmed_at
      # t.datetime :confirmation_sent_at
      # t.string   :unconfirmed_email # Only if using reconfirmable

      ## Lockable
      # t.integer  :failed_attempts, default: 0, null: false # Only if lock strategy is :failed_attempts
      # t.string   :unlock_token # Only if unlock strategy is :email or :both
      # t.datetime :locked_at


      # Uncomment below if timestamps were not included in your original model.
      # t.timestamps null: false
    end
    remove_index(:users, :name => 'index_users_on_email')
    add_index :users, :email,                unique: true
    add_index :users, :reset_password_token, unique: true
    # add_index :users, :confirmation_token,   unique: true
    # add_index :users, :unlock_token,         unique: true
  end

  def self.down
    # By default, we don't want to make any assumption about how to roll back a migration when your
    # model already existed. Please edit below which fields you would like to remove in this migration.
    raise ActiveRecord::IrreversibleMigration
  end
end
```

My project migration file does have a reference to Users it is created after the users

```

class CreateProjects < ActiveRecord::Migration[5.0]
  def change
    create_table :projects do |t|
      t.string :name
      t.string :header1
      t.string :header2
      t.string :description
      t.string :screen_img_url
      t.string :host_url
      t.references :user, foreign_key: true

      t.timestamps
    end
  end
end

```

**Comment by jshawl** [comment] 2016-10-15 18:18
I'm not sure what the issue is - my recommendation would be to forget about devise till Monday - move forward with your project. Assume the current user is the first user

**Comment by merubin** [comment] 2016-10-15 18:22
I may just drop the db and re-create it without the email address at all.  I have all the scripts I used.  I may just try this on my branch I'm working off of. or create a new one off this.  I can continue work from the master.  Thanks for looking

**Comment by amaseda** [comment] 2016-10-17 13:24
Going to close this one but please re-open if you have any more questions on this topic.

**Comment by merubin** [comment] 2016-10-17 18:56
I decided not to use devise as All I need is the concept of the current user.  So I decided to just introduce a session  variable.  I installed Sessions and now I'm getting the following errors:

rails aborted!
ArgumentError: 'Session' is not a supported controller name. This can lead to potential routing problems. See http://guides.rubyonrails.org/routing.html#specifying-a-controller-to-use
/U

**Comment by jshawl** [comment] 2016-10-17 18:58
what are the steps to reproduce this issue?

**Comment by jshawl** [comment] 2016-10-17 19:00
visiting a url? running rake db:seeds?

also does it identify any code? do you have a controller named session?

**Comment by merubin** [comment] 2016-10-17 19:00
1 install sessions
$ rails g controller sessions
Then I added 
  def new
    @user = User.new
  end 
to the sessions controller

Then I added:
resource :session   # Add this after the resources already in the file.

**Comment by merubin** [comment] 2016-10-17 19:01
Running Rails Routes

**Comment by jshawl** [comment] 2016-10-17 19:01
what does your sessions controller look like? can you push to github?

**Comment by merubin** [comment] 2016-10-17 19:03
It's pushed on the sessions branch

**Comment by jshawl** [comment] 2016-10-17 19:04
I think you have a typo - https://github.com/merubin/portfolio_management_system/blob/0c05eb8fbdf39209cbc68b50c2525e0ddb4d7c03/app/controllers/sessions_controller.rb#L2

**Comment by merubin** [comment] 2016-10-17 19:11
Yes I saw the typo it was caused white I was reviewing.  I have fixed the plural controllers and pushed back up to get hub still same issue.

class SessionController < ApplicationController
$ rails routes
rails aborted!
ArgumentError: 'Session' is not a supported controller name. This can lead to potential routing problems. See http://guides.rubyonrails.org/routing.html#specifying-a-controller-to-use
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/mapper.rb:313:in `bloc

**Comment by jshawl** [comment] 2016-10-17 19:17
ooo I belive it's this line - https://github.com/merubin/portfolio_management_system/blob/sessions/config/routes.rb#L19 should be lowercase right?

**Comment by merubin** [comment] 2016-10-17 19:19
That did it!  Thank you!

**Comment by jshawl** [comment] 2016-10-17 19:19
👍

**Closed as completed by jshawl** 2016-10-17 19:19 UTC
