### ISSUE TITLE
why does a class show undefined sometimes and other times it renders fine in view?

### ISSUE THREAD

**Issue by kairajohnson** [ga-wdi-exercises/project2#506] opened 2016-03-22 22:48 UTC
I have noticed in ruby that a method can bed fine and bring up no errors and if I re write the same code or add the same code to somewhere else in the view, it shows up undefined..... Why is that? If the method was defined before, why does that change? to make sure I didn't misspell or had any syntex errors, I commented out part of my code and post is still undefined even thought that my class and table. I'm not understanding that.... 
​
Below is my html file. I receive an error that "post" is not defined. This same code has worked until I added the same image_tag to my sidebar..... lines 27 and 43

``` erb
<div id = "featured-post" style="text-align: center; padding-top: 35px;">
  <%= image_tag Post.last.featured_image, style:'max-width: 700px; height: auto'%>
  <h1 class="featured_title" style="padding-top: 15px; color: pink;"><%= Post.last.title %></h1>
  <div class="featured_content" style="padding: 0px 100px; width: 800px; margin: 0 auto;"><%= Post.last.content %></div>
</div>
​
​
<div id="section-title" style="padding-top: 100px;">
<h1 class="section-title-left"style="width: 70%;"> In Her Closet </h1>
<h1 class="section-title-right"style="width: 30%;"> Recent Posts </h1>
</div>
​
<div id="main">
​
<table id="grid" style="width: 66.66%; float: left;">
<% @posts.in_groups_of(2, false) do |post_column| %>
<tr>
    <% for post in post_column %>
    <td class="grid-post" style="width: 33.33%;">
      <h2 class="caption"><%= post.title %>
      </h2>
      <div id="thumbnail">
      <%= image_tag post.featured_image, :class=>"thumbnail"%>
      </div>
      <p><%= truncate(Post.last.content, length: 200) %></p>
    </td>
    <% end %>
  <tr>
  <% end %>
</table>
​
<div id="sidebar" style="float: right;">
<div id="recent-posts">
  <h2> Recent Posts </h2>
  <table>
    <tr>
      <td>
        <div id="thumbnail-small">
        <%= image_tag post.featured_image, :class=>"thumbnail"%>
        </div>
      </td>
    <td>
      <%= post.title %>
      <p><%= truncate(Post.last.content, length: 200) %></p>
    </td>
  </tr>
</table>
</div> -->
</div>
```

**Comment by kairajohnson** [comment] 2016-03-22 22:57
https://github.com/kairajohnson/live-unapologetically

**Comment by kairajohnson** [comment] 2016-03-22 23:24
so I am noticing the problem is when something is duplicated. like, i have post.title in one div and in another I have post.title. It's fine when there is just one but when two, it gives me an error. With the second being ignored, what is the proper way to reuse a method? I don't fully understand how to access instances outside of the controller throughout the app

**Comment by RobertAKARobin** [comment] 2016-03-23 03:32
The problem isn't duplication. Your second `post.title` is outside of your `<% for post in post_column %>` loop. `post` only exists inside that loop. Take a look at where your `do`s and `end`s are.

**Comment by RobertAKARobin** [comment] 2016-03-23 13:56
It's been a while, so I'm going to close this. Feel free to reopen or post a new issue if necessary.

**Closed as completed by RobertAKARobin** 2016-03-23 13:56 UTC
